### ISSUE TITLE
Migrate module to Voxpupuli

### ISSUE THREAD

**Issue by ekohl** [voxpupuli/puppet-pbuilder#14]
* [x] Ask one of the Administrators to add you to the incoming-migrations team.
* [x] At that point you can transfer your own repository.
* [x] If migrating a module from puppetlabs, re-enable github issues.
* [x] Verify that all webhooks except travis are disabled.
* [x] Update the README.md with a description of the deprecation and a link to the new module location.
* [x] Release a copy of your module to the ‘puppet’ forge account.
* [x] Add the module to our modulesync setup.
* [x] Ask an admin to add the collaborators team to the module’s Collaborators & Teams ‘Teams’ list with Write permissions (e.g. https://github.com/voxpupuli/puppet-gitlab/settings/collaboration)).
* [x] Execute modulesync for this module.
* [x] Create a Jira issue at https://tickets.puppetlabs.com and ask to deprecate the old module (and approve the new one if the old one was approved as well).
* [x] Ensure that there isn’t a CONTRIBUTING.md file in the docroot. Our modulesync will place one at .github/CONTRIBUTING.md. Please enhance our existing template if the version in the docroot contains useful parts.
* [x] Ensure that the module has a correct LICENSE file in the docroot that matches the mentioned license in the metadata.json.

**Comment by ekohl** [comment]
https://github.com/voxpupuli/modulesync_config/pull/700 & https://github.com/voxpupuli/puppet-pbuilder/pull/15 should take care of most steps.

@raphink for the last point:
22756500542b316d84b0267b9b893afd6bf285a5 says it's GPL-3 in LICENSE
c398f4d8fc6a01381bae07b68287d473fb7b61e8 says Apache-2.0 in metadata.json

Can you clarify which license is correct? I'm guessing GPL-3 since that's older.

**Comment by raphink** [comment]
Let's go with Apache-2.0, as that's what we've used for our modules usually.

**Comment by alexjfisher** [comment]
Since most of the code is yours, @mcanevet can you confirm you're ok with Apache-2.0?

**Comment by mcanevet** [comment]
Yes, let's go with Apache-2.0

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-pbuilder/pull/16 should fix the license.

**Comment by ekohl** [comment]
This is pretty much done. In https://github.com/voxpupuli/puppet-pbuilder/pull/17 I also remove some left over GPL copyright texts which were in the manifests. After that I'll see about releasing a new version so that the old one can be deprecated.

Note that the steps state the deprecation needs to happen via JIRA ticket but [there's an API](https://forgeapi.puppet.com/#operation/deprecateModule) nowadays. We should come up with a `curl` example for it.

**Comment by ekohl** [comment]
> After that I'll see about releasing a new version so that the old one can be deprecated.

https://github.com/voxpupuli/puppet-pbuilder/pull/23

**Comment by ekohl** [comment]
It was finally released. @raphink I know you already left camptocamp, but do you still have access to run this? Or can you ask anyone with access?
```
curl -H 'Authorization: Bearer API_KEY' -X PATCH https://forceapi.puppet.com/v3/modules/camptocamp-builder -H 'Content-Type: application/json' -d '{"action": "deprecate", "params": {"reason": "Migrated to Vox Pupuli", "replacement_slug": "puppet-pbuilder"}}'
```

`API_KEY` can be retrieved from https://forge.puppet.com/

**Comment by raphink** [comment]
No, I don't have access to this secret @ekohl. Maybe @saimonn does for ex.

**Comment by ekohl** [comment]
I opened https://tickets.puppetlabs.com/browse/FORGE-662 for now.

**Comment by ekohl** [comment]
https://forge.puppet.com/modules/camptocamp/pbuilder now has a deprecation, meaning we can finally consider this completed.
